bpm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView


urlpatterns = [
    path("",TemplateView.as_view(template_name="home.html"), name="home"),
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("", include("django.contrib.auth.urls")),
    path("", include("spotify.urls"))
]

spotify/models.py
from django.conf import settings
from django.db import models
# from django.db.models import CheckConstraint, Q, F
from django.utils import timezone

from annoying.fields import AutoOneToOneField
from zoneinfo import ZoneInfo
import datetime

# Spotify user ID (Ex.: wizzler) https://developer.spotify.com/documentation/web-api/#spotify-uris-and-ids
# spotify display name https://developer.spotify.com/documentation/web-api/reference/#/operations/get-current-users-profile
class SpotifyUser(models.Model):
    def __str__(self):
        return self.spotify_display_name
    
    user = AutoOneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    spotify_user_id = models.CharField(max_length=50)
    spotify_display_name = models.CharField(max_length=191)
    access_token = models.CharField(max_length=300)
    refresh_token = models.CharField(max_length=300)
    expiration = models.DateTimeField(default=timezone.make_aware(datetime.datetime.min, ZoneInfo('UTC')))
    scope = models.CharField(max_length=191)
    date_auth = models.DateTimeField(default=timezone.make_aware(datetime.datetime.min, ZoneInfo('UTC')))

# Spotify ID for playlists (Ex.: 3cEYpjA9oz9GiPac4AsH4n) https://developer.spotify.com/documentation/web-api/reference/#/operations/get-playlist
class BpmPlaylist(models.Model):
    def __str__(self):
        return self.playlist_id
    
    spotify_user = models.ForeignKey(SpotifyUser, on_delete=models.PROTECT)
    playlist_id = models.CharField(max_length=200, unique=True)
    name = models.CharField(max_length=50, verbose_name="Playlist name")
    created_datetime = models.DateTimeField(default=timezone.now)
    last_update_datetime = models.DateTimeField(default=timezone.now)
    bpm_start = models.PositiveSmallIntegerField(verbose_name="Starting bpm", help_text="Please enter a positive integer. It must be smaller or equal to the ending bpm.")
    bpm_end = models.PositiveSmallIntegerField(verbose_name="Ending bpm", help_text="Please enter a positive integer. It must be greater or equal to the starting bpm.")
    multiples_bpm = models.BooleanField(default=True, verbose_name="Include multiples", help_text="If you select this, tracks with bpms that are multiples of the ones in the selected bpm range will also be added to the playlist. This means faster songs may be added, but slower songs will not be added.")

    # class Meta:
    #     constraints = [
    #         CheckConstraint(
    #             check=Q(bpm_start__lte=F('bpm_end')), 
    #             name='bpm_check'
    #         ) 
    #     ]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  <title>{% block title %}bpm{% endblock %}</title>
</head>
<body class="d-flex flex-column min-vh-100">
  {% include 'includes/messages.html' %}

  <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <a href="{% url 'home' %}" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">bpm</a>
    <!-- TO DO add after creating other pages -->
    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
      <li><a href="#" class="nav-link px-2 link-secondary"></a></li>
    </ul>
    <div class="col-md-3 text-right">
      {% block auth %}{% endblock %}
    </div>
  </header>

  <main class="px-3 pb-2">
    <div id="content">
      {% block content %}{% endblock %}
    </div>
  </main>

  <footer class="footer mt-auto d-flex flex-wrap justify-content-between align-items-center py-3 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <p class="text-muted">&copy; 2022 Sungmin Oh</p>
    </div>
    <!--TO DO add other social media-->
    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li>
        <a class="text-muted" href="https://github.com/codingminnow/bpm.git">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-github" viewBox="0 0 24 24">
            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
          </svg>
        </a>
      </li>
    </ul>
        
  </footer>
  
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block auth %}
{% include 'includes/auth.html' %}
{% endblock %}

{% block content %}
{# user authenticated/authorized Spotify account #}
{% if user.spotifyuser.spotify_user_id %}
  <h1>My Dashboard</h1>

  <p class="text-sm-right">Total: {{ user.spotifyuser.bpmplaylist_set.all.count }}</p>

  <div class="table-responsive"></div>
    <table class="table table-striped table-sm">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">BPM - start</th>
        <th scope="col">BPM - end</th>
        <th scope="col">Multiples allowed?</th>
        <th scope="col">Actions</th>
      </tr>
      {% for playlist in user.spotifyuser.bpmplaylist_set.all %}
        <tr>
          <td>{{playlist.name}}</td>
          <td>{{playlist.bpm_start}}</td>
          <td>{{playlist.bpm_end}}</td>
          <td>{{playlist.multiples_bpm}}</td>
          <td>
            <a class="btn btn-dark btn-sm" href="{% url 'updateplaylist' playlist.playlist_id %}">Update</a>
            <a class="btn btn-dark btn-sm" href="{% url 'deleteplaylist' playlist.playlist_id %}">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>

  <a class="btn btn-primary" href="{% url 'createplaylist' %}">Create bpm playlist</a>
  <a class="btn btn-primary" href="{% url 'syncplaylists' %}">Sync playlists with Spotify</a>

{% else %}
  <p>No Spotify account linked.</p>
  <a class="btn btn-primary" href="{% url 'spotifylogin' %}">Login to Spotify Account</a> |
{% endif %}
{% endblock %}